name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Validate bash scripts syntax
        shell: bash
        run: |
          bash -n install.sh
          bash -n backup_state.sh
          bash -n bootstrap.sh
          bash -n bin/piper

      - name: Validate Python CLI import
        shell: bash
        run: |
          python - <<'PY'
          import importlib.util, pathlib
          p = pathlib.Path('src/piper_cli.py')
          spec = importlib.util.spec_from_file_location('piper_cli', str(p))
          mod = importlib.util.module_from_spec(spec)
          spec.loader.exec_module(mod)
          print('IMPORTED', hasattr(mod, 'main'), hasattr(mod, 'build_parser'))
          PY
